# Generated by Django 6.0.2 on 2026-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_options_alter_groupchatmembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер файла (байт)'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='MIME тип'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота изображения'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина изображения'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_voice',
            field=models.BooleanField(default=False, verbose_name='Голосовое сообщение'),
        ),
        migrations.AddField(
            model_name='message',
            name='video_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность видео (сек)'),
        ),
        migrations.AddField(
            model_name='message',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/', verbose_name='Превью видео'),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность голоса (сек)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
